import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Appbar } from "./components/Appbar";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import DarkModeToggle from "./DarkModeToggle";
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ["latin"] });

 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Crypto Wallet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cn}(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}  ${inter.className}`}>
        <Appbar/>
        <DarkModeToggle/>
        <NextTopLoader height={4} color="#2299DD" />
        {children}
      </body>
    </html>
  );
}
